### ISSUE TITLE
Double mouse cursor.

### ISSUE THREAD

**Issue by knxwille** [royalgraphx/SideswipeOnQEMU#2]
-display sdl,gl=on,show-cursor=on --> causes double mouse cursor on some android distors. I advice replace with "show-cursor=off"
-device virtio-tablet-pci also causes mouse problems. I advice -device virtio-mouse is better.
GRALLOC=gbm --> Doesn't work some android distros.

**Comment by royalgraphx** [comment]
``Doesn't work some android distros``, this repository is fully curated to only work with the following Bliss ISO provided in the instructions. You're seeing double mouse cursor, because your android image isn't patched with the touchscreen fixes. If android is seeing your input as a cursor, thats wrong. the mouse problems are related to the same fix. to have relative mouse input, the mouse itself is not resetting position. please use the mentioned ISO. or if you wish to proceed with custom ISO, modify the files to apply the following patches

Android Patch:
https://github.com/royalgraphx/SideswipeOnQEMU/tree/main/isolated_touch_fix/system/usr/idc

QEMU SRC Build Patch:
https://github.com/royalgraphx/qemu-sideswipe/blob/wx86_64/patches/QEMU_Virtio_Tablet.patch
